spherical-volume-rendering/svr-algorithm

polarCoordinateTraversal.m
And it's my first time using matlab woohoo
=> complete angular hit function, haven't gone through testing

polarCoordinateTraversal_old.m, radial_hit_old.m
- Code cleanup.
- Add loop boundary condition that states ```current_voxel_ID_r > 0```. This ensures the loop ends when the ray has exited our circle.
=> Add loop boundary condition, code cleanup.

polarCoordinateTraversal_old.m
- Does an early check to return if the ray never enters the circle.
=> Add no ray entrance early check.

polarCoordinateTraversalTest.m, polarCoordinateTraversal_old.m, radial_hit_old.m
- Add test suite for ```polarCoordinateTraversal_old```
- Add semicolon in ```radial_hit_old```.
- Update clarity on what ```polarCoordinateTraversal_old``` returns.
=> Add test suite, small cleanups.

angular_hit.m, polarCoordinateTraversal_dotprod.m, radial_hit_dotprod.m
Plus a change to angular_hit returns.
=> New functions

polarCoordinateTraversalTest.m
Fix the following test cases:
TestRayBeginInsideCircleAndDoesNotGoThroughOrigin
TestNegativeXandY 
TestBeginAtThetaBoundaryInOrthogonal
=> Test case fix

polarCoordinateTraversalTest.m
testRayInterSectThetaBoundaryOutsideTheCircle
testRayDoesNotGoThroughTheInnermostVoxel
testRayTraverseSingleVoxel
testRayEndsInsideCircle
testRayWithPositiveXNegativeY
testRayWithNegativeXPositiveY
testRayBeginTimeDiffThan0
testRayWithOddNumAngularSections
testRaySlightIntersect
=> Add new testcases

angular_hit.m, polarCoordinateTraversal.m, polarCoordinateTraversalTest.m, radial_hit.m
Addressed previous PR comments
=> Test Passers (address previous PR comments)

SphericalTraversal/sphericalCoordinateTraversal.m
Initialization phase updates for 3D.
=> Update Init. phase to inclue phi

polarCoordinateTraversal.m
- Change ```t_end``` to the minimum of ```t_end, t_grid```.
- Simplify the traversal phase by checking for ```<=``` case rather than checking to see if ```tMaxR == tMaxTheta```. 
- Add comments to each part for clarity.
- Remove duplication of the code that inserts the new voxels in the voxel lists.
- In the case where neither ```tMaxR``` nor ```tMaxTheta``` are within bounds, just return early.
This PR passes all the cases that previously passed (which does not include the 2 tests with ambiguous edge cases in relation to angular hit).
=> Simplify traversal phase.

SphericalTraversal/SphericalCoordinateTraversalExample.m, SphericalTraversal/angular_hit.m, SphericalTraversal/azimuthal_hit.m, SphericalTraversal/radial_hit.m, SphericalTraversal/sphericalCoordinateTraversal.m, SphericalTraversal/sphericalCoordinateTraversalTest.m, angular_hit.m, polarCoordinateTraversal.m, polarCoordinateTraversalTest.m
1. Updated spherical traversal files to include 3D variable names
2. Removed redundant code for parallel cases in angular hit for both 2D and 3D cases
3. Completed azimuthal hit (identical to angular hit with renaming of vars)
4. Added modulo function for angular ID (Chris' update)
=> Multiple edits

cpp/ray.h, cpp/spherical_volume_rendering_util.cpp, cpp/spherical_volume_rendering_util.h
- Added documentation.
- Implemented radialHit().
- Removed code duplication with Cythonized version.
- Implemented function timeOfIntersectionAt() in Ray.h with documentation.
=> Add timeOfIntersection to ray, implement radialHit(), documentation.

sphereTestPlot.py
=> Add requirements, titles to plots of sphereTestPlot.py

sphereTestPlot.py
- Move constants outside of editable section.
- Fix while loop condition
- Scale time appropriately.
=> Fix while loop condition, move normals.

.gitignore, cpp/testing/CMakeLists.txt, cpp/testing/spherical_volume_rendering_test.cpp
- Adds necessary terminal commands.
- Add run_svr_tests command to CMake.
=> Update testing framework for cpp

cpp/vec3.h
This addresses #56. This will be used for debugging purposes.
=> Add assertion for division by 0.

matlab/spherical-traversal/sphericalCoordinateTraversalTest.m
Added:
testRayTravelsAlongXAxis
testRayTravelsAlongYAxis
testRayParallelToXZPlane
testRayParallelToYZPlane
testRayNegXPosYZ
testRayNegXPosYZ
testRayNegZPosXY(stil fixing)
Added some potential test cases ideas
=> Add new test cases for spherical traversal

cpp/cython/CythonSVR_test.py, cpp/cython/printTests.py
Update tests to use Matt's much more intuitive structure array.
=> Update Cython tests.

cpp/spherical_volume_rendering_util.cpp, cpp/spherical_voxel_grid.h
To mitigate future bugs and other indexing errors, I've transitioned the for loops into STL algorithms.
=> Remove raw for loops.

cpp/testing/SVR_benchmarks.cpp
Add a case where all rays intersect the sphere in an orthographic project.
=> Orthographic ray trace benchmark.

matlab/spherical-traversal/sphericalCoordinateTraversalTest.m
testRayNegXYZ
testOddRadialSections
testOddAngularSections
testOddAziSections
testLargeRadialSections
testLargeAngularSections
testLargeAziSections
=> add test cases

cpp/spherical_volume_rendering_util.cpp
- Remove last raw loop in calculateVoxelID().
=> Remove last raw loop.

cpp/spherical_volume_rendering_util.cpp
=> Create algorithm template for CalculateVoxelID() to avoid returning a dummy value with adjacent_find.

cpp/benchmarks/benchmark_SVR.cpp, cpp/spherical_volume_rendering_util.cpp, cpp/spherical_voxel_grid.h
Code cleanup.
Clang formatted code.
None.
=> Code clangy tidy.

cpp/cython/tests/test_walk_spherical_volume.py, cpp/spherical_volume_rendering_util.cpp, cpp/tests/CMakeLists.txt, cpp/tests/test_SVR.cpp
=> Add tests for no ray entrance (tangential hit), many rays in X, Y planes.

cpp/tests/CMakeLists.txt
Please include a summary of the change and and provide any related issues or pull requests.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
=> Add --coverage for gcov for CI.

cpp/spherical_volume_rendering_util.cpp
Please include a summary of the change and and provide any related issues or pull requests.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
=> Remove print statement.

cpp/spherical_volume_rendering_util.cpp
=> Remove floating point comparisons where close cases are unlikely.

cpp/spherical_volume_rendering_util.cpp
=> Add back some of the fp calculations.

.circleci/config.yml, cpp/tests/CMakeLists.txt, cpp/tests/ci_tests.cpp
Add Large CI tests to be run in the background.
=> Add large CI tests.

cpp/tests/ci_tests.cpp
Add more checks within the CI test.
=> Add more checks within the CI test.

cpp/tests/ci_tests.cpp
=> Add more integrated tests.

cpp/tests/ci_tests.cpp
=> Add more CI tests, verify general angular voxel ordering and bounds.

cpp/tests/ci_tests.cpp
=> Add fail statement in the case of voxel check failure

cpp/tests/ci_tests.cpp
See title. Now, radial check says the following:
1. If its solely a radial hit, then the next radial voxel must be current+1 or current-1.
2. Otherwise, it may be current+1, current-1, or current+0.
=> Strengthen the requirements of the radial check.

cpp/spherical_volume_rendering_util.cpp, cpp/tests/ci_tests.cpp
Removal of unnecessary variables, clang tidied.
=> Code cleanup.

.circleci/config.yml, README.md, cpp/benchmarks/CMakeLists.txt, cpp/benchmarks/benchmark_svr.cpp, cpp/tests/CMakeLists.txt, cpp/tests/test_svr.cpp
=> Update binary names, documentation for name change to snake case.

.circleci/config.yml, cpp/spherical_volume_rendering_util.cpp
=> Fix circleci, Attempt to ignore cythonized code in coverage.

cpp/tests/CMakeLists.txt, cpp/tests/continuous_integration_tests.cpp
=> Randomize major axis used in random input CI test.

cpp/spherical_volume_rendering_util.cpp, cpp/tests/continuous_integration_tests.cpp
=> Fix bug in CI tests comparing a bool with float.

cpp/tests/continuous_integration_tests.cpp
=> Use const & for SphericalVoxel.

cpp/tests/continuous_integration_tests.cpp
=> const & for SphericalVoxel in printVoxelInformation().

cpp/floating_point_comparison_util.h, cpp/ray.h, cpp/spherical_volume_rendering_util.cpp, cpp/spherical_volume_rendering_util.h, cpp/spherical_voxel_grid.h, cpp/tests/test_svr.cpp, cpp/vec3.h
This should be an octant, since it represent a 4th of the upper hemisphere. Please let me know if this is incorrect.
=> Fix name of SVR test.

cpp/vec3.h
=> Add constexpr to UnitVec.
