spherical-volume-rendering/svr-algorithm

polarCoordinateTraversal.m

- Update location of early exit since ```tStepR``` is calculated within ```radial_hit``` now.

Update early exit of polarCoordinateTraversal.

---

polarCoordinateTraversal.m
radial_hit.m

Addition off flag for the case when the ray passes through, sequentially, two radial boundaries of equal radius. Previously, this case caused a skip ahead in te radial hit check. Also, fix to tStepR block.

Addition of flag, fixes for tStepR

---

polarCoordinateTraversal.m
radial_hit.m

- Code cleanup for ```polarCoordinateTraversal```, ```radial_hit```.
- Anything that can be initialized outside of ```radial_hit``` has been moved.
- I've changed the location of ``` if (current_voxel_ID_r + tStepR <= 0), return; end```. Before, this was going to exit early even if the next step was not a radial step. This should only occur IF the next step is a radial step.
- Added documentation for new arguments.

Code clean-up, initialization outside of hot loop, fix early exit.

---

matlab/spherical-traversal/sphericalCoordinateTraversalTest.m

- Added a test that slightly changes the ray direction in the XY-plane.
- Added two tests, parallel to XY and XZ planes. (**Note**: These may change when the code is updated, since its along an angular boundary).
**Note:** Trying this test in the XZ plane, i.e. ray direction = [1, 1, 1.5] claims that only 5 voxel traversals occur. Its difficult to determine whether this is true or not, even with spherePlot.py. Does this mean the ray is exiting from the top early?

Add simple spherical traversal tests.

---

matlab/polar-traversal/polarCoordinateTraversal.m

We find the expected chord length by calculating t2-t1 from the initialization phase. We also add an accumulator to keep track of the total time we spend on traversal. Right now, Different inputs result in fluctuations of the accumulator compares to the expected chord length. The problem might lie in failing to properly print out acc.

Chord length test

---

.gitignore
cpp/cython/CythonSVR_test.py
cpp/spherical_volume_rendering_util.cpp
cpp/spherical_volume_rendering_util.h
cpp/spherical_voxel_grid.h
cpp/testing/spherical_volume_rendering_test.cpp

The cpp version did not pass the basic spherical tests. This PR fixes this. All tests (both cpp and Cythonized) provided in the test files below pass. If  you haven't been tracking my recent changes, it may be easier to read the entire file without diffs.
- Change tStep to a signed type, since it can be negative.
- Add constants ABS_EPSILON, REL_EPSILON.
- Copied a few test cases from #89 with corrected voxels.
- Add function KnLessThan(), which ensures ```a *is strictly less than* b```.
- Instead of checking the conditionals 
```
t *strictly less than* tMax && tMax *strictly less than* t_end
``` 
in the while loop, I've added these to the corresponding functions radialHit(), angularHit(), azimuthalHit().
- Update generalizedPlaneHit() to use strictlyLessThan for comparisons with a, b.
- …

Fix cpp version to pass spherical tests.

---

cpp/cython/CythonSVR_test.py
cpp/cython/printTests.py
cpp/spherical_volume_rendering_util.cpp
cpp/testing/spherical_volume_rendering_test.cpp

See: #103 for specifics.
The removal of updateVoxelBoundarySegment() helped a lot in terms of performance bottleneck.

[cpp] Add Ariel's new updates.

---

cpp/spherical_volume_rendering_util.cpp
cpp/spherical_voxel_grid.h
cpp/testing/benchmarking.cpp

- Added a benchmark for multiple ray intersection.
- Optimized the initialization of voxel boundary segments; Since the boundary segments for the maximum radius will be the same for all rays through a similar sphere, this can be done in the construction of the SphericalVoxelGrid.
- In CalculateVoxelID(), I was using ```const std::vector``` instead of ```const std::vector &``` which was creating a copy on each call. Fixing this bug allowed for a major speedup.

Add multiple ray intersection benchmark, Optimize initialization of voxel boundary segments, and more.

---

cpp/ray.h
cpp/spherical_volume_rendering_util.cpp
cpp/spherical_volume_rendering_util.h
cpp/spherical_voxel_grid.h
cpp/testing/CMakeLists.txt
cpp/testing/SVR_benchmarks.cpp
cpp/testing/SVR_tests.cpp
cpp/vec3.h

- Add namespaces to avoid naming collisions.
- Optimize timeOfIntersectionAt() to avoid branch prediction slowdowns. Upon construction, a non-zero direction is determined.
- Add [] operator to Vec3.
- Remove unnecessary fluff in CMake.
- Add orthographic ray trace benchmark.
- Other cleanup.

Add namespaces, optimize Ray functions, add orthographic benchmark.

---

cpp/spherical_volume_rendering_util.cpp
cpp/testing/SVR_benchmarks.cpp

After benchmarking std::max versus inlined MAX function, I found no significant difference.

Revert back to std::max, std::min

---

cpp/spherical_volume_rendering_util.cpp
cpp/spherical_voxel_grid.h
cpp/vec3.h

First, we can exit early if there is no intersection.
Then, since a tangential hit and a normal radial intersection are only different when calculating tStepR, we only need a boolean for that case.
To avoid branch prediction slowdown, we can simply create an array {0, -1, 1}. Since ```true == 1``` and ```false == 0```, we can use some quick algebra to determine the right step value.
Also uses constexpr for EPSILON values, vec3, and spherical_voxel_grid.

Simplify radialHit() logic.

---

cpp/ray.h
cpp/spherical_volume_rendering_util.cpp
cpp/spherical_voxel_grid.h
cpp/testing/SVR_tests.cpp

In both angular and azimuthal hit, we were calculating
```p, p_end, v``` separately. These represent (respectively) the ray segment at time t, the ray segment at time t_end, and the free vector represented by ```p_end - p```. I've replaced:
```p``` ->```P1```
```p_end``` -> ```P2```
```v``` -> ```ray_segment```
```P2``` never changes since ```t_end``` never changes.
We can calculate ```P1, ray_segment``` once with each iteration, and pass it in each plane hit function respectively. This means we update ```P1, ray_segment``` once per iteration (using ```updateRaySegmentPoints()``` rather than twice per iteration, and ```P2``` once per sphericalVoxelTraversal call. 
Next, I've added a collinear_times array to get rid of two branch predictions per traversal and reduce a calculation to once …

Reduce floating point calculations in angular, azimuthal hit.

---

cpp/ray.h
cpp/spherical_volume_rendering_util.cpp
cpp/vec3.h

So using std::vector in radialHit() to calculate multiple values for times_gt_t was causing a bit of a slowdown. Calling clear() is expensive, and similar for iterating through. 
I saw that we only used times_gt_t[0] ever to calculate the intersection_time, or tMaxR.
Then, it is sufficient to find the first time greater than t.
The one issue would be in the tangential hit case, where intersection_times[0] and intersection_times[1] are equal, but there are not two times greater than t.
In other words, ```ray.timeOfIntersectionAt(v - d_a) == ray.timeOfIntersectionAt(v + d_a)```, one of them is greater than t, but the other isn't. This contradicts itself; therefore, we can lessen the logic a bit.
In other news, 
- Remove the use of a REL_EPSILON. Now, all FP equality is determined by an …

Remove need of std::vector in radialHit(), only use ABS_EPSILON to determine FP equality.

---

cpp/spherical_volume_rendering_util.cpp
cpp/spherical_voxel_grid.h
cpp/vec3.h

- Pre-initializes delta radii calculations in the sphericalVoxelGrid. These can be accessed by index. This greatly reduces calculations in the initialization phase.
- Updates generalizedPlaneHit() to remove two knLessThan() duplications.
- Other clean up.

Pre-initialize deltaRadii calculations.

---

cpp/spherical_volume_rendering_util.cpp
cpp/spherical_voxel_grid.h

- Use previously calculated deltaRadii, deltaRadiiSquared to avoid duplicated calculations.
- Use a double[] to avoid a branch prediction when calculating the previous index.
- Use std::min, std::max on size_t instead of floats.
- Avoid calculating ```X - rh_data.rsvdMinusVSquared()``` unless the condition is true. This is derived in the following way:
```
=> X - ray_sphere_vector_dot - v * v < 0.0
=> X - rh_data.rsvdMinusVSquared() < 0.0
=> X < rh_data.rsvdMinusVSquared()
```
- Early exits for generalizedPlaneHit() in the case where the calculated ```t``` value(s) are not within bounds.
- Save ray->NZD as a member of RaySegment.
This PR lessens the 256^2 rays, 128^3 voxels orthographic trace to less than 0.95 seconds consistently on my MacBook Air 2013.

Reduce radialHit() calculations.

---

cpp/cython/cython_SVR_tests.py
cpp/spherical_volume_rendering_util.cpp
cpp/testing/SVR_benchmarks.cpp
cpp/testing/SVR_tests.cpp

- See: #144 for test cases. **(WIP)**
- Added a few more test cases for a large number of radial sections. If we use a large number of radial sections and a not-so-large sphere max radius, our algorithm breaks down. What "large" means still needs to be ironed out. This also addresses #145
- Fixed the orthographic benchmark so that each ray travels the entirety of the sphere, i.e. ```radial_voxels = 1, 2, ... , N-1, N, N-1, ... , 2, 1```
- The original benchmarks were incorrect. Not all rays were going entirely through the sphere. I will add new benchmarks here soon, verifying the ray travels the entirety of the sphere.
- Fix issues for when t_begin != 0.0 - This has to do with the ray sphere vector used with certain calculations. The ray_sphere_vector at t = 0.0 must be used for …

Add corner case tests for when the ray originates inside the sphere, address orthographic case.

---

README.md
cpp/benchmarks/benchmark_SVR.cpp
cpp/cython/cython_SVR.pyx
cpp/cython/cython_SVR_setup.py
cpp/cython/tests/test_walk_spherical_volume.py
cpp/spherical_volume_rendering_util.cpp
cpp/spherical_volume_rendering_util.h
cpp/spherical_voxel_grid.h
cpp/tests/CMakeLists.txt
cpp/tests/test_SVR.cpp

Updated the sectored sphere implementation so that the minimum boundaries are part of the grid. Now, the deltas are determined by (max_bound_X - min_bound_X) / num_X_sections
Fixes the tangential hit bug. 
- Before:
```
const bool is_tangential_hit =  isEqual(intersection_times[0], intersection_times[1])
```
- After:
```
const bool is_tangential_hit = intersection_times[0] > t && isEqual(intersection_times[0], intersection_times[1])
```

Fix Tangential Hit Bug, Update sectored sphere implementation.

---

cpp/spherical_volume_rendering_util.cpp

Clean up RadialHit() to use early exit in the case of a tangential hit.
Clean up some boolean logic in AngularHit().
Rename variables in the main traversal for clarity.

Cleanup, boolean logic simplification.

---

README.md
cpp/benchmarks/benchmark_SVR.cpp
cpp/cython/tests/test_walk_spherical_volume.py
cpp/spherical_volume_rendering_util.cpp
cpp/tests/.travis.yml
cpp/tests/CMakeLists.txt
cpp/tests/build.sh
cpp/tests/test_SVR.cpp
cpp/vec3.h

Author's note: I've been meaning to get around to this for awhile. I've finally had some time to implement it.
Currently, our radialHit function isn't very efficient. With each call, we were calculating the length between the next point of intersection and the sphere center. This is very expensive requiring 10+ floating point operations and a std::sqrt(). We also had many branch predictions, based off whether the radial step transition has occurred or not. Lastly, we were unnecessarily calculating times for 4 separate points of intersection with each call of radialHit. I now propose a simplified version, that is broken down into two cases. Here, a radial step transition is defined as the transition from positive tStepR to negative tStepR. This is necessary since radial voxels are defined …

Optimize & simplify radialHit(), add test for radial voxel 0 and sphere not at origin.

---

cpp/cython/tests/test_walk_spherical_volume.py
cpp/spherical_volume_rendering_util.cpp
cpp/spherical_voxel_grid.h
cpp/tests/test_SVR.cpp

The common case is likely to be rays outside the spherical volume. Here we optimize for the uncommon case -- we begin at the inner most radius and work our way outwards. We need to see if there's a simpler way to start from the outermost radial voxel to the innermost.
This is done by using the squared euclidean distance of ```ray.pointAtParameter(t_begin) - sphereCenter()```, and comparing it to the squared radius. While the squared euclidean distance is less than the squared radius, increment the radial voxel.
No functionality has changed.
- Added a few more tests, which led to an early exit case when the current radial voxel == 0.
- Removed a duplicate test case.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any …

Optimize radial voxel initialization for the common case; add more tests.

---

cpp/spherical_volume_rendering_util.cpp
cpp/tests/ci_tests.cpp

- Documentation for CI_tests.
- Use static_cast to avoid implicit casts.

Documentation, static_cast to avoid implicit cast

---

cpp/spherical_volume_rendering_util.cpp
cpp/tests/continuous_integration_tests.cpp

before:
```
if (t_sphere_entrance < t_begin && t_sphere_exit < t_begin) {
return {};
}
```
after: 
```
if (t_sphere_exit < t_begin) {
return {};
}
```
It is perfectly reasonable for the ray to enter the sphere before t_begin. There is no need to check this. 
- Update the CI tests readability and reduce duplication and complexity.

Remove unnecessary floating point comparison in radial initialization.

---

cpp/benchmarks/benchmark_svr.cpp
cpp/cython/cython_SVR.pyx
cpp/cython/tests/test_walk_spherical_volume.py
cpp/ray.h
cpp/spherical_volume_rendering_util.cpp
cpp/spherical_volume_rendering_util.h
cpp/spherical_voxel_grid.h
cpp/tests/continuous_integration_tests.cpp
cpp/tests/test_svr.cpp

The yt version of walk_volume does not have a t_begin, and unitizes time and the ray direction. Our functionality should be similar. Doing so will require some refactoring.
- Change ```t_end``` to ```max_t```.
- Set cythonized version ```max_t``` default value to 1.0
- Remove t_begin. This is not used in yt's ```walk_volume```, and its removal allows for the removal of unnecessary calculations. If one wants the ray to start at a different t_begin, the origin can be changed.
- Unitize the ray direction.
- Unitize the ray time. This is done by using ```max_t```. The documentation changes in the following way:
```
// max_t is the unitized time for which the ray may travel. It is used in the following
// linear function: ray_travel_duration = time_to_entrance + sphere.diameter() * max_t
// If …
```

Unitize time, ray direction. Add CI tests for when ray is within the sphere.

---

cpp/spherical_volume_rendering_util.cpp
cpp/spherical_volume_rendering_util.h
cpp/spherical_voxel_grid.h

I'm attempting to get the traversal working for the case that N_polar != N_azimuth, which seems to have some catches in it when doing volume rendering in yt.

attempt to add enter_t exit_t to Voxels and fix some bounds logic
